<?php

namespace ContainerXbQZ7L0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Security_Command_RoleHierarchyDump_LazyService extends App_KernelProductionDebugContainer
{
    /**
     * Gets the private '.security.command.role_hierarchy_dump.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.security.command.role_hierarchy_dump.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('debug:security:role-hierarchy', [], 'Dump the role hierarchy as a Mermaid flowchart', false, #[\Closure(name: 'security.command.role_hierarchy_dump', class: 'Symfony\\Bundle\\SecurityBundle\\Command\\SecurityRoleHierarchyDumpCommand')] fn (): \Symfony\Bundle\SecurityBundle\Command\SecurityRoleHierarchyDumpCommand => ($container->privates['security.command.role_hierarchy_dump'] ?? $container->load('getSecurity_Command_RoleHierarchyDumpService')));
    }
}
