<?php

namespace ContainerXbQZ7L0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_EventManagerDebugCommandService extends App_KernelProductionDebugContainer
{
    /**
     * Gets the private 'doctrine.event_manager_debug_command' shared service.
     *
     * @return \Doctrine\ORM\Tools\Console\Command\Debug\DebugEventManagerDoctrineCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Tools/Console/Command/Debug/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Tools/Console/Command/Debug/DebugEventManagerDoctrineCommand.php';

        $container->privates['doctrine.event_manager_debug_command'] = $instance = new \Doctrine\ORM\Tools\Console\Command\Debug\DebugEventManagerDoctrineCommand(($container->services['doctrine'] ?? self::getDoctrineService($container)));

        $instance->setName('doctrine:debug:event-manager');

        return $instance;
    }
}
