<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJq75Czn\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJq75Czn/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJq75Czn.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJq75Czn\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerJq75Czn\App_KernelProdContainer([
    'container.build_hash' => 'Jq75Czn',
    'container.build_id' => '0c73f757',
    'container.build_time' => 1768924616,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJq75Czn');
