<?php

namespace ContainerFL0xBWU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_GEx8y9aService extends App_KernelDevContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.gEx8y9a' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Symfony\Component\Notifier\Messenger\MessageHandler((new \Symfony\Component\Notifier\Transport(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['notifier.transport_factory.null'] ?? $container->load('getNotifier_TransportFactory_NullService'));
        }, 1)))->fromStrings([])), []);

        if (isset($container->privates['.messenger.handler_descriptor.gEx8y9a'])) {
            return $container->privates['.messenger.handler_descriptor.gEx8y9a'];
        }

        return $container->privates['.messenger.handler_descriptor.gEx8y9a'] = $instance;
    }
}
