<?php

namespace ContainerFL0xBWU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropertyInfo_ConstructorExtractorService extends App_KernelDevContainer
{
    /*
     * Gets the private 'property_info.constructor_extractor' shared service.
     *
     * @return \Symfony\Component\PropertyInfo\Extractor\ConstructorExtractor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['property_info.constructor_extractor'] = new \Symfony\Component\PropertyInfo\Extractor\ConstructorExtractor(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['property_info.phpstan_extractor'] ??= new \Symfony\Component\PropertyInfo\Extractor\PhpStanExtractor());
            yield 1 => ($container->privates['property_info.php_doc_extractor'] ??= new \Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor());
            yield 2 => ($container->privates['property_info.reflection_extractor'] ??= new \Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor());
        }, 3));
    }
}
