<?php

namespace ContainerFL0xBWU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_ValidatorService extends App_KernelDevContainer
{
    /*
     * Gets the private 'twig.validator' shared service.
     *
     * @return \Symfony\Bridge\Twig\Validator\Constraints\TwigValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->privates['twig.validator'])) {
            return $container->privates['twig.validator'];
        }

        $instance = new \Symfony\Bridge\Twig\Validator\Constraints\TwigValidator($a);

        if (isset($container->privates['twig.validator'])) {
            return $container->privates['twig.validator'];
        }

        return $container->privates['twig.validator'] = $instance;
    }
}
