<?php

namespace ContainerJJx5e5q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_SigningSerializer_SigningKeyService extends App_KernelProductionContainer
{
    /*
     * Gets the private '.messenger.signing_serializer.signing_key' shared service.
     *
     * @return \string
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.signing_serializer.signing_key'] = $container->getParameter('kernel.secret');
    }
}
