<?php

namespace ContainerJJx5e5q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_WG_ORBvService extends App_KernelProductionContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.WG.oRBv' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService'));

        if (isset($container->privates['.messenger.handler_descriptor.WG.oRBv'])) {
            return $container->privates['.messenger.handler_descriptor.WG.oRBv'];
        }

        $instance = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Symfony\Component\Mailer\Messenger\MessageHandler($a), []);

        if (isset($container->privates['.messenger.handler_descriptor.WG.oRBv'])) {
            return $container->privates['.messenger.handler_descriptor.WG.oRBv'];
        }

        return $container->privates['.messenger.handler_descriptor.WG.oRBv'] = $instance;
    }
}
