<?php

namespace ContainerJJx5e5q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_EventManagerDebugCommandService extends App_KernelProductionContainer
{
    /*
     * Gets the private 'doctrine.event_manager_debug_command' shared service.
     *
     * @return \Doctrine\ORM\Tools\Console\Command\Debug\DebugEventManagerDoctrineCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['doctrine.event_manager_debug_command'] = $instance = new \Doctrine\ORM\Tools\Console\Command\Debug\DebugEventManagerDoctrineCommand(($container->services['doctrine'] ?? self::getDoctrineService($container)));

        $instance->setName('doctrine:debug:event-manager');

        return $instance;
    }
}
