<?php

namespace ContainerJJx5e5q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Access_ClosureVoterService extends App_KernelProductionContainer
{
    /*
     * Gets the private 'security.access.closure_voter' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authorization\Voter\ClosureVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.authorization_checker'] ?? self::getSecurity_AuthorizationCheckerService($container));

        if (isset($container->privates['security.access.closure_voter'])) {
            return $container->privates['security.access.closure_voter'];
        }

        $instance = new \Symfony\Component\Security\Core\Authorization\Voter\ClosureVoter($a);

        if (isset($container->privates['security.access.closure_voter'])) {
            return $container->privates['security.access.closure_voter'];
        }

        return $container->privates['security.access.closure_voter'] = $instance;
    }
}
