<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJJx5e5q\App_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJJx5e5q/App_KernelProductionContainer.php') {
    touch(__DIR__.'/ContainerJJx5e5q.legacy');

    return;
}

if (!\class_exists(App_KernelProductionContainer::class, false)) {
    \class_alias(\ContainerJJx5e5q\App_KernelProductionContainer::class, App_KernelProductionContainer::class, false);
}

return new \ContainerJJx5e5q\App_KernelProductionContainer([
    'container.build_hash' => 'JJx5e5q',
    'container.build_id' => '08124aaf',
    'container.build_time' => 1768924407,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJJx5e5q');
