<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXbQZ7L0\App_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXbQZ7L0/App_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/ContainerXbQZ7L0.legacy');

    return;
}

if (!\class_exists(App_KernelProductionDebugContainer::class, false)) {
    \class_alias(\ContainerXbQZ7L0\App_KernelProductionDebugContainer::class, App_KernelProductionDebugContainer::class, false);
}

return new \ContainerXbQZ7L0\App_KernelProductionDebugContainer([
    'container.build_hash' => 'XbQZ7L0',
    'container.build_id' => '79672ae2',
    'container.build_time' => 1768923948,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXbQZ7L0');
