<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFL0xBWU\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFL0xBWU/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerFL0xBWU.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerFL0xBWU\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerFL0xBWU\App_KernelDevContainer([
    'container.build_hash' => 'FL0xBWU',
    'container.build_id' => '7af6908d',
    'container.build_time' => 1768924169,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFL0xBWU');
