<?php

namespace ContainerJq75Czn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Signing_Messenger_DefaultSerializerService extends App_KernelProdContainer
{
    /*
     * Gets the private '.signing.messenger.default_serializer' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\Serialization\SigningSerializer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.signing.messenger.default_serializer'] = new \Symfony\Component\Messenger\Transport\Serialization\SigningSerializer(($container->privates['.messenger.transport.native_php_serializer'] ??= new \Symfony\Component\Messenger\Transport\Serialization\PhpSerializer()), \Symfony\Component\String\LazyString::fromCallable(#[\Closure(name: '.messenger.signing_serializer.signing_key', class: 'string')] fn () => ($container->privates['.messenger.signing_serializer.signing_key'] ?? $container->load('get_Messenger_SigningSerializer_SigningKeyService'))), ['Symfony\\Component\\Process\\Messenger\\RunProcessMessage', 'Symfony\\Component\\Console\\Messenger\\RunCommandMessage']);
    }
}
